# Generated by Django 5.2.17 on 2026-09-04 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcedureType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Тип депиляции')),
            ],
            options={
                'verbose_name': 'Тип депиляции',
                'verbose_name_plural': 'Типы депиляций',
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Зона депиляции')),
            ],
            options={
                'verbose_name': 'Зона депиляции',
                'verbose_name_plural': 'Зоны депиляций',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_minutes', models.PositiveSmallIntegerField(verbose_name='Продолжительность процедуры')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена')),
                ('is_active', models.BooleanField(default=True)),
                ('procedure_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.proceduretype', verbose_name='Тип депиляции')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.zone', verbose_name='Зона депиляции')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
    ]
