# Generated by Django 5.2.17 on 2026-09-04 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proceduretype',
            options={'verbose_name': 'Тип процедуры', 'verbose_name_plural': 'Типы процедуры'},
        ),
        migrations.AlterModelOptions(
            name='zone',
            options={'verbose_name': 'Зона процедуры', 'verbose_name_plural': 'Зоны процедуры'},
        ),
        migrations.AlterField(
            model_name='proceduretype',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Тип процедуры'),
        ),
        migrations.AlterField(
            model_name='service',
            name='procedure_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.proceduretype', verbose_name='Тип процедуры'),
        ),
        migrations.AlterField(
            model_name='service',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.zone', verbose_name='Зона процедуры'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Зона процедуры'),
        ),
    ]
