# Generated by Django 5.2.17 on 2026-09-04 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_proceduretype_options_alter_zone_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proceduretype',
            options={'verbose_name': 'Тип процедуры', 'verbose_name_plural': 'Типы процедур'},
        ),
        migrations.AlterModelOptions(
            name='zone',
            options={'verbose_name': 'Зона', 'verbose_name_plural': 'Зоны'},
        ),
        migrations.AlterField(
            model_name='service',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=8, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='service',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.zone', verbose_name='Зона'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Зона'),
        ),
    ]
