# Generated by Django 5.2.17 on 2026-09-05 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_proceduretype_options_alter_zone_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_showcased',
            field=models.BooleanField(default=False),
        ),
    ]
