# Generated by Django 5.2.17 on 2026-09-05 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_service_is_showcased'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='is_showcased',
            field=models.BooleanField(default=False, verbose_name='На витрине'),
        ),
    ]
