# Generated by Django 5.2.17 on 2026-09-05 20:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_service_is_showcased'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField(verbose_name='Начало визита')),
                ('status', models.CharField(choices=[('planned', 'Запланирована'), ('cancelled', 'Отменена'), ('done', 'Завершена'), ('no_show', 'Не пришёл')], default='planned', max_length=20, verbose_name='Статус')),
                ('total_duration_minutes', models.PositiveSmallIntegerField(default=0, verbose_name='Длительность визита')),
                ('total_price', models.DecimalField(decimal_places=0, default=0, max_digits=8, verbose_name='Стоимость визита')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booking', to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
                ('services', models.ManyToManyField(related_name='booking', to='main.service', verbose_name='Выбранные услуги')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
                'ordering': ['-starts_at'],
            },
        ),
    ]
