# Generated by Django 5.2.17 on 2026-09-13 12:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_starts', models.TimeField(default=datetime.time(10, 0), verbose_name='Начало рабочего дня')),
                ('work_ends', models.TimeField(default=datetime.time(18, 0), verbose_name='Конец рабочего дня')),
                ('min_hours_before_visit', models.PositiveSmallIntegerField(default=3, verbose_name='Минимум часов до визита')),
                ('slot_step_minutes', models.PositiveSmallIntegerField(default=15, verbose_name='Шаг слота записи')),
            ],
            options={
                'verbose_name': 'Настройки записи',
                'verbose_name_plural': 'Настройки записи',
            },
        ),
    ]
