# Generated by Django 5.2.17 on 2026-09-13 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_worksettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksettings',
            name='friday',
            field=models.BooleanField(default=True, verbose_name='Пятница'),
        ),
        migrations.AddField(
            model_name='worksettings',
            name='monday',
            field=models.BooleanField(default=True, verbose_name='Понедельник'),
        ),
        migrations.AddField(
            model_name='worksettings',
            name='saturday',
            field=models.BooleanField(default=True, verbose_name='Суббота'),
        ),
        migrations.AddField(
            model_name='worksettings',
            name='sunday',
            field=models.BooleanField(default=True, verbose_name='Воскресенье'),
        ),
        migrations.AddField(
            model_name='worksettings',
            name='thursday',
            field=models.BooleanField(default=True, verbose_name='Четверг'),
        ),
        migrations.AddField(
            model_name='worksettings',
            name='tuesday',
            field=models.BooleanField(default=True, verbose_name='Вторник'),
        ),
        migrations.AddField(
            model_name='worksettings',
            name='wednesday',
            field=models.BooleanField(default=True, verbose_name='Среда'),
        ),
    ]
