# Generated by Django 5.2.17 on 2026-09-13 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_worksettings_friday_worksettings_monday_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField(verbose_name='Начало нерабочего времени')),
                ('ends_at', models.DateTimeField(verbose_name='Конец нерабочего времени')),
                ('comment', models.CharField(blank=True, max_length=100, verbose_name='Комментарии')),
            ],
            options={
                'verbose_name': 'Нерабочее время',
                'verbose_name_plural': 'Нерабочее время',
                'ordering': ['-starts_at'],
            },
        ),
    ]
