# Generated by Django 5.2.17 on 2026-09-14 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_timeoff'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['starts_at'], 'verbose_name': 'Запись', 'verbose_name_plural': 'Записи'},
        ),
        migrations.AlterModelOptions(
            name='timeoff',
            options={'ordering': ['starts_at'], 'verbose_name': 'Нерабочее время', 'verbose_name_plural': 'Нерабочее время'},
        ),
    ]
