# Generated by Django 5.2.17 on 2026-09-16 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_booking_options_alter_timeoff_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='proceduretype',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
    ]
