# Generated by Django 5.2.17 on 2026-09-17 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_proceduretype_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='worksettings',
            options={'verbose_name': 'Настройки рабочего времени', 'verbose_name_plural': 'Настройки рабочего времени'},
        ),
    ]
