# Generated by Django 5.2.17 on 2026-09-17 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_worksettings_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksettings',
            name='lunch_ends',
            field=models.TimeField(blank=True, null=True, verbose_name='Конец обеда'),
        ),
        migrations.AddField(
            model_name='worksettings',
            name='lunch_starts',
            field=models.TimeField(blank=True, null=True, verbose_name='Начало обеда'),
        ),
    ]
